<script type="text/javascript" src="<%=request.getContextPath()%>/resource/js/jquery.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/resource/js/jquery.form.js"></script>
<!-- Facebox jQuery Plugin -->
<link type="text/css" href="<%=request.getContextPath()%>/resource/facebox/facebox.css"
	type="text/css" media="screen" rel="stylesheet" />
<script type="text/javascript" src="<%=request.getContextPath()%>/resource/facebox/facebox.js"></script>
<!-- jQuery WYSIWYG Plugin -->
<script type="text/javascript" src="<%=request.getContextPath()%>/admin/resources/scripts/jquery.wysiwyg.js"></script>
<!-- jQuery Datepicker Plugin -->
<script type="text/javascript"
	src="<%=request.getContextPath()%>/resource/My97DatePicker/WdatePicker.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/resource/treegrid/treegrid.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/resource/dataTables/js/jquery.dataTables.js"></script>